### ISSUE TITLE
Visit Google HQ (or move to where Feross lives)

### ISSUE THREAD

**Issue by ChrisMorrisOrg** [ChrisMorrisOrg/Life#13]

**Comment by feross** [comment]
I live walking distance away from Google :)

**Comment by ChrisMorrisOrg** [comment]
Okay, maybe I'll update the title to "move where Feross lives".

**Comment by ChrisMorrisOrg** [comment]
I forgot to close this issue back in June!

**Comment by feross** [comment]
Ahaha nice!
